# Generated by Django 5.2.1 on 2025-05-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='departmentName',
            new_name='department',
        ),
    ]
