# Generated by Django 5.2.1 on 2025-05-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_departmentname_department_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='date',
            new_name='dateOfJoining',
        ),
    ]
